### ISSUE TITLE
how to generate raw PDUI

### ISSUE THREAD

**Issue by BenxiaHu** [YiPeng-Gao/scDaPars#1]
Hello,
     I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
Best,

**Comment by YiPeng-Gao** [comment]
Hi, Thanks for your interest in scDaPars. Please view the attached website for detailed instructions for generating raw PDUI.

http://lilab.research.bcm.edu/dldcc-web/lilab/Lei/DaPars2_Documentation/DaPars2.html

Hope this helps!

> Hello,
> I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
> Best,

**Comment by YiPeng-Gao** [comment]
> Hello,
> I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
> Best,

**Comment by learner-bioinformation** [comment]
> Hi, Thanks for your interest in scDaPars. Please view the attached website for detailed instructions for generating raw PDUI.
> 
> http://lilab.research.bcm.edu/dldcc-web/lilab/Lei/DaPars2_Documentation/DaPars2.html
> 
> Hope this helps!
> 
> > Hello,
> > I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
> > Best,

**Comment by learner-bioinformation** [comment]
> Hello,
> I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
> Best,
Hi, has the problem of generating the raw PDUI been solved? Can you open the website http://lilab.research.bcm.edu/dldcc-web/lilab/Lei/DaPars2_Documentation/DaPars2.html? How did you generate the raw PDUI?
Best,

**Comment by learner-bioinformation** [comment]
> Hello,
> I want to run scDaPars to analyze scRNA-seq. scDaPars takes as input the raw PDUI generated by DaPars2. Would you like to tell me how to run DaPars2? I have checked the DaPars2 (https://github.com/3UTR/DaPars2), it does not show how to run it.
> Best,
Hi, has the problem of generating the raw PDUI been solved? Can you open the website http://lilab.research.bcm.edu/dldcc-web/lilab/Lei/DaPars2_Documentation/DaPars2.html? How did you generate the raw PDUI?
Best,

**Comment by YiPeng-Gao** [comment]
Sorry, Please check the website https://leilisysbio.github.io/DaPars2_Documentation/DaPars2.html.
I will also update the github page with the pipeline for scDaPars.

Hope this will help!

**Comment by learner-bioinformation** [comment]
Hi, is there a test file? I don’t know how the file "sequencing_depth_file=mapping_bam_location_with_depth.txt" is generated?
Best,

**Comment by YiPeng-Gao** [comment]
We will update the GitHub page for DaPars2 shortly with test files. Thanks for the reminder!

**Comment by learner-bioinformation** [comment]
hi, how do I get the sequencing depth file? I found that the sequencing depth file (mapping_bam_location_with_depth.txt) cannot be generated with bedtools.
Best.

**Comment by YiPeng-Gao** [comment]
> hi, how do I get the sequencing depth file? I found that the sequencing depth file (mapping_bam_location_with_depth.txt) cannot be generated with bedtools.
> Best.

Hi, you can use "samtools flagstat bam_file > flagstat.txt" to get the sequencing depth for each sample, and then compile into one txt file formatted as "mapping_bam_location_with_depth.txt".

**Comment by learner-bioinformation** [comment]
Thanks, i will try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiPeng-Gao/scDaPars"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 凌晨0:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiPeng-Gao/scDaPars] how to generate raw PDUI (#1)





  
hi, how do I get the sequencing depth file? I found that the sequencing depth file (mapping_bam_location_with_depth.txt) cannot be generated with bedtools.
 Best.
  
Hi, you can use "samtools flagstat bam_file &gt; flagstat.txt" to get the sequencing depth for each sample, and then compile into one txt file formatted as "mapping_bam_location_with_depth.txt".

**Comment by learner-bioinformation** [comment]
Hi, I would like to ask if it is the hg38 file for cellranger align, can the UCSC hg19 bed file (the test set given by dapars2) be used in step 1 of dapars2?
Best,

**Comment by YiPeng-Gao** [comment]
> Hi, I would like to ask if it is the hg38 file for cellranger align, can the UCSC hg19 bed file (the test set given by dapars2) be used in step 1 of dapars2?
> Best,

I would suggest you generate a hg38 bed file for that.

**Comment by ghost** [comment]
"samtools flagstat bam_file > flagstat.txt "  Which value is used in the result file for subsequent analysis
85207970 + 0 in total (QC-passed reads + QC-failed reads)
5350668 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
73549948 + 0 mapped (86.32% : N/A)
79857302 + 0 paired in sequencing
39928651 + 0 read1
39928651 + 0 read2
62977510 + 0 properly paired (78.86% : N/A)
63902424 + 0 with itself and mate mapped
4296856 + 0 singletons (5.38% : N/A)
173078 + 0 with mate mapped to a different chr
127302 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by YiPeng-Gao** [comment]
> "samtools flagstat bam_file > flagstat.txt " Which value is used in the result file for subsequent analysis
> 85207970 + 0 in total (QC-passed reads + QC-failed reads)
> 5350668 + 0 secondary
> 0 + 0 supplementary
> 0 + 0 duplicates
> 73549948 + 0 mapped (86.32% : N/A)
> 79857302 + 0 paired in sequencing
> 39928651 + 0 read1
> 39928651 + 0 read2
> 62977510 + 0 properly paired (78.86% : N/A)
> 63902424 + 0 with itself and mate mapped
> 4296856 + 0 singletons (5.38% : N/A)
> 173078 + 0 with mate mapped to a different chr
> 127302 + 0 with mate mapped to a different chr (mapQ>=5)

I would recommend use the number of mapped reads. In your case, that is "73549948".
