### ISSUE TITLE
10x data

### ISSUE THREAD

**Issue by Lianqw** [YiPeng-Gao/scDaPars#10]
Hello!
For 10x example data,I want to know which GSMs in GEO132044 you used in scDapars, because there are too many samples in GEO132044.

**Comment by YiPeng-Gao** [comment]
Human PBMCs GSM3837156, GSM3837157, GSM3837158, GSM3837159, GSM3837170, GSM3837171, GSM3837172, GSM3837173.

**Comment by YiPeng-Gao** [comment]
If you open the SRA run selector, you can choose filters: 10X chromium (V2), homo sapiens, female to get the GSM.

**Comment by Lianqw** [comment]
There are 8 GSMs, then I want to know if you use cellranger count to process 8 SRRs at once? Or use cellranger count separately ?

**Comment by YiPeng-Gao** [comment]
No, you combine the first 4 as read 1 and the remaining 4 as read 2 before cell ranger.
