### ISSUE TITLE
differential 3'UTR

### ISSUE THREAD

**Issue by BenxiaHu** [YiPeng-Gao/scDaPars#12]
Hello,
    I just ran scDaPars and got the results, it seems that scDaPars does not perform differential 3'UTR between differential cells or clusters.

![image](https://user-images.githubusercontent.com/12387462/120489479-a9193400-c385-11eb-9e14-76b4cdfc5e75.png)

**Comment by YiPeng-Gao** [comment]
> Hello,
> I just ran scDaPars and got the results, it seems that scDaPars does not perform differential 3'UTR between differential cells or clusters.
> 
> ![image](https://user-images.githubusercontent.com/12387462/120489479-a9193400-c385-11eb-9e14-76b4cdfc5e75.png)

scDaPars output PDUI values. If you want to figure out differential 3'UTR, you can check the updated manuscript in https://genome.cshlp.org/content/early/2021/05/25/gr.271346.120.abstract for how we identify differential 3'UTR.

**Comment by BenxiaHu** [comment]
thanks. so here you just compare the entire PDUI between different cell types, not PDUI of the same genes between different cell types, right?

![image](https://user-images.githubusercontent.com/12387462/120499532-25177a00-c38e-11eb-883a-d4fcf0a826a8.png)

**Comment by YiPeng-Gao** [comment]
> thanks. so here you just compare the entire PDUI between different cell types, not PDUI of the same genes between different cell types, right?
> 
> ![image](https://user-images.githubusercontent.com/12387462/120499532-25177a00-c38e-11eb-883a-d4fcf0a826a8.png)

Actually, We only compare PDUIs for the same genes between different cell types. Here PDUI celltype1 means average PDUI for the gene of interest in cell type 1.
