### ISSUE TITLE
dapars2 result from 10x data

### ISSUE THREAD

**Issue by Lianqw** [YiPeng-Gao/scDaPars#13]
A chromosome has only a few lines. Is your result the same?
![image](https://user-images.githubusercontent.com/72534628/120579443-172f2b00-c45a-11eb-9848-0495e09cdda8.png)

**Comment by YiPeng-Gao** [comment]
The results from 10X data have significantly fewer genes than those from Smart-seq2. You can try to adjust different parameters to get more genes.

**Comment by Lianqw** [comment]
Thank you very much!
