### ISSUE TITLE
cell type information

### ISSUE THREAD

**Issue by BenxiaHu** [YiPeng-Gao/scDaPars#2]
Hello,
    when I try to run scDaPars on one public scRNA-seq, I reaslized that I need to provide the cell type information.
scDaPars.res.umap = umap(t(scDaPars.res))
scDaPars.res.umap.data = data.frame(scDaPars.res.umap$layout)
colnames(scDaPars.res.umap.data) = c("Dim1", "Dim2")
scDaPars.res.umap.data$cellType = **cell_type$source_name**

My question is that scDaPars can identify cell clusters, not depends known cell typ information?

**Comment by YiPeng-Gao** [comment]
> Hello,
> when I try to run scDaPars on one public scRNA-seq, I reaslized that I need to provide the cell type information.
> scDaPars.res.umap = umap(t(scDaPars.res))
> scDaPars.res.umap.data = data.frame(scDaPars.res.umap$layout)
> colnames(scDaPars.res.umap.data) = c("Dim1", "Dim2")
> scDaPars.res.umap.data$cellType = **cell_type$source_name**
> 
> My question is that scDaPars can identify cell clusters, not depends known cell typ information?

The cell type information is used as ground truth to evaluate if the clustering result is correct. The clustering itself does not require any prior cell type information.

**Comment by BenxiaHu** [comment]
great.
