### ISSUE TITLE
scDaPars

### ISSUE THREAD

**Issue by ghost** [YiPeng-Gao/scDaPars#3]
scDaPars.res = scDaPars(raw_PDUI_file = "/DaPars2_Test_data_result_temp.chr3.txt",out_dir = "/scDaPars_result",filter_gene_thre = 0.2,filter_cell_thre = 0.1)
show error :

Error in RANN::nn2(t(mat_pcs), k = 30) : 
  Cannot find more nearest neighbours than there are points

**Comment by YiPeng-Gao** [comment]
> scDaPars.res = scDaPars(raw_PDUI_file = "/DaPars2_Test_data_result_temp.chr3.txt",out_dir = "/scDaPars_result",filter_gene_thre = 0.2,filter_cell_thre = 0.1)
> show error :
> 
> Error in RANN::nn2(t(mat_pcs), k = 30) :
> Cannot find more nearest neighbours than there are points

Can you share the size of your dataset?

**Comment by ghost** [comment]
Run DaPars2, Output format: 
![image](https://user-images.githubusercontent.com/54733697/118761730-8415c300-b8a7-11eb-8b16-e89a4b3920be.png)

/scDaPars/Example/Dapars_hESC_combined_all_chromosome.txt comes out with a column of numbers. What should I do with the data after Dapars2 runs? Dapars_hESC_combined_all_chromosome.txt What information is the number in the first column?

![image](https://user-images.githubusercontent.com/54733697/118762044-1d44d980-b8a8-11eb-8e67-ac312f661a17.png)

The reason for the error when running scDapars software is that the results of DaPars2 software running are missing the first column, so scDapars cannot be run directly.

best

**Comment by huangrongbioinfomation** [comment]
What is this calculation formula?
![image](https://user-images.githubusercontent.com/54733697/119095107-70539380-ba44-11eb-9dc7-6263786cafdf.png)

**Comment by learner-bioinformation** [comment]
Hi, I want to ask whether the output result of DaPars2 can be directly used as the input of scDaPars. When I input directly, the following error appears. How can I solve the following error?
![1621582697](https://user-images.githubusercontent.com/83384159/119100541-a562e480-ba4a-11eb-8fc0-b9bfb6d97e5f.jpg)
![1621583092(1)](https://user-images.githubusercontent.com/83384159/119101406-89ac0e00-ba4b-11eb-8f8d-9b22b1b3653d.png)

**Comment by YiPeng-Gao** [comment]
> Run DaPars2, Output format:
> ![image](https://user-images.githubusercontent.com/54733697/118761730-8415c300-b8a7-11eb-8b16-e89a4b3920be.png)
> 
> /scDaPars/Example/Dapars_hESC_combined_all_chromosome.txt comes out with a column of numbers. What should I do with the data after Dapars2 runs? Dapars_hESC_combined_all_chromosome.txt What information is the number in the first column?
> 
> ![image](https://user-images.githubusercontent.com/54733697/118762044-1d44d980-b8a8-11eb-8e67-ac312f661a17.png)
> 
> The reason for the error when running scDapars software is that the results of DaPars2 software running are missing the first column, so scDapars cannot be run directly.
> 
> best

scDaPars runs directly using DaPars results. The first column are put in by mistake. I will update the github example file. You can run the file without the first column.

**Comment by ghost** [comment]
Number of samples: 7
Data size: 428K，
Thank you for updating the file as soon as possible
Use DaPars result files to directly analyze scDaPars, show error :
![image](https://user-images.githubusercontent.com/54733697/119212766-11962480-baed-11eb-8e58-41a6c119881f.png)

**Comment by ghost** [comment]
Number of samples: 7
Data size: 428K，
![image](https://user-images.githubusercontent.com/54733697/119219012-c93f2c80-bb15-11eb-95cd-9e825f98d78d.png)
Use DaPars result files to directly analyze scDaPars, show error :
![image](https://user-images.githubusercontent.com/54733697/119219015-d22ffe00-bb15-11eb-944a-8e668961e114.png)

**Comment by huangrongbioinfomation** [comment]
The DaPars result file can run the script, Maybe you need to modify the code？
Processing_raw_PDUI_matrix.R

![image](https://user-images.githubusercontent.com/54733697/119232356-8ef67f00-bb57-11eb-8b1e-35c1bd71833e.png)

**Comment by YiPeng-Gao** [comment]
> Number of samples: 7
> Data size: 428K，
> ![image](https://user-images.githubusercontent.com/54733697/119219012-c93f2c80-bb15-11eb-95cd-9e825f98d78d.png)
> Use DaPars result files to directly analyze scDaPars, show error :
> ![image](https://user-images.githubusercontent.com/54733697/119219015-d22ffe00-bb15-11eb-944a-8e668961e114.png)

The problem here is you have too few samples. The RANN:nn2() function has a parameter k = 30. Therefore, it will give this error if the number of samples is fewer than 30 (which does not make sense for single-cell studies). Normally, in single-cell studies, you will have at least hundreds of cells.

**Comment by ghost** [comment]
Number of samples: 35
Data size: 1.7M
show error :Error in 1:npc : argument of length 0
![image](https://user-images.githubusercontent.com/54733697/119437027-dcd5d780-bd4f-11eb-8339-36e921881f1f.png)

**Comment by YiPeng-Gao** [comment]
> Number of samples: 35
> Data size: 1.7M
> show error :Error in 1:npc : argument of length 0
> ![image](https://user-images.githubusercontent.com/54733697/119437027-dcd5d780-bd4f-11eb-8339-36e921881f1f.png)

The code and example file has been updated and the code is working smoothly right now. I cannot help you debug when I don't have your data. You can use the R scripts provided in GitHub to run code line by line to figure out the reason for this error.  It seems your error happens when scDaPars selects PCs (npc) that explain >40% of the total variance for clustering. You can start from there.

**Comment by ghost** [comment]
Hello, can I add your contact information? Emails have been sent to your mailbox before, beginning with 181

**Comment by YiPeng-Gao** [comment]
> Hello, can I add your contact information? Emails have been sent to your mailbox before, beginning with 181

You can email me at yipengg@bcm.edu
