### ISSUE TITLE
Dapars_hESC_combined_all_chromosome.txt

### ISSUE THREAD

**Issue by ghost** [YiPeng-Gao/scDaPars#4]
Run DaPars2, Output format, /scDaPars/Example/Dapars_hESC_combined_all_chromosome.txt comes out with a column of numbers. What should I do with the data after Dapars2 runs? Dapars_hESC_combined_all_chromosome.txt What information is the number in the first column?
![image](https://user-images.githubusercontent.com/54733697/119009885-26c46380-b9c6-11eb-8f57-4c6177ed02b1.png)

**Comment by ghost** [comment]
Use https://github.com/3UTR/DaPars2 test data to generate ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt, use ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt to run the scDAPA software, an error appears as shown in the figure. 
After searching for the reason, I found that the https://github.com/YiPeng-Gao/scDaPars/issues/ sample file has more information in the first column than the result file of DaPars2 operation, so I want to consult how the information in the first column is generated.
 ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt 19K
![image](https://user-images.githubusercontent.com/54733697/119068523-f527b880-ba16-11eb-8adb-a59c7a36ee0f.png)
![image](https://user-images.githubusercontent.com/54733697/119068529-fbb63000-ba16-11eb-90b3-908c6ab580d4.png)

**Comment by ghost** [comment]
There is no mention of a column of information in the literature， 
![image](https://user-images.githubusercontent.com/54733697/119097848-caa22380-ba47-11eb-8dc0-860d304d7eea.png)

**Comment by YiPeng-Gao** [comment]
> Use https://github.com/3UTR/DaPars2 test data to generate ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt, use ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt to run the scDAPA software, an error appears as shown in the figure.
> After searching for the reason, I found that the https://github.com/YiPeng-Gao/scDaPars/issues/ sample file has more information in the first column than the result file of DaPars2 operation, so I want to consult how the information in the first column is generated.
> ./DaPars2_Test_data_chr3/DaPars2_Test_data_result_temp.chr3.txt 19K
> ![image](https://user-images.githubusercontent.com/54733697/119068523-f527b880-ba16-11eb-8adb-a59c7a36ee0f.png)
> ![image](https://user-images.githubusercontent.com/54733697/119068529-fbb63000-ba16-11eb-90b3-908c6ab580d4.png)

I think this is because the example file only have 2 samples.... it does not make sense to cluster 2 samples..

**Comment by YiPeng-Gao** [comment]
The example file has been updated.
