### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by ghost** [YiPeng-Gao/scDaPars#5]
Is the flow chart missing 3 steps and not displayed?

1. selected reads with correct unique molecular identifier (UMI) using Drop-seq tools FilterBAM (Macosko et al. 2015) 
2. remove reads with duplicated UMIs using UMI-tools dedup (Smith et al. 2017). 
3. merged reads originated from same cells together and generated one BAM file for each single cell

![image](https://user-images.githubusercontent.com/54733697/119212923-27581980-baee-11eb-90e9-24e777d66577.png)

![image](https://user-images.githubusercontent.com/54733697/119213016-cc72f200-baee-11eb-9396-f84e630b3573.png)

**Comment by YiPeng-Gao** [comment]
> Is the flow chart missing 3 steps and not displayed?
> 
> 1. selected reads with correct unique molecular identifier (UMI) using Drop-seq tools FilterBAM (Macosko et al. 2015)
> 2. remove reads with duplicated UMIs using UMI-tools dedup (Smith et al. 2017).
> 3. merged reads originated from same cells together and generated one BAM file for each single cell
> 
> ![image](https://user-images.githubusercontent.com/54733697/119212923-27581980-baee-11eb-90e9-24e777d66577.png)
> 
> ![image](https://user-images.githubusercontent.com/54733697/119213016-cc72f200-baee-11eb-9396-f84e630b3573.png)

This is standard procedure for any 10X (UMI-based protocol) single cell procedure, not specific to scDaPars that is why it is not included in the pipeline.
