### ISSUE TITLE
confounding factor

### ISSUE THREAD

**Issue by BenxiaHu** [YiPeng-Gao/scDaPars#6]
Hello,
    For example, I have 2 scRNAseq datasets (AD and control), each consisting of 10 samples.  But each sample has some different features, such as age and sex.  When we analyze differential expression for such bulk RNAseq or scRNAseq, we usually regress out these possible confounding factors(age and sex). my question is that DaPars or scDaPars regresses out those confounding factors?

**Comment by YiPeng-Gao** [comment]
Currently we do not regress out confounding factors.
